# Generated by Django 2.1.5 on 2019-01-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profesori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emriProfi', models.CharField(max_length=50)),
                ('mbiemriProfi', models.CharField(max_length=50)),
                ('nrPersonalProfi', models.CharField(max_length=50)),
                ('emailProfi', models.EmailField(max_length=50)),
                ('pas', models.CharField(max_length=50)),
                ('idLenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lenda')),
            ],
        ),
    ]
