# Generated by Django 2.1.5 on 2019-01-14 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_perioda'),
    ]

    operations = [
        migrations.CreateModel(
            name='nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlera', models.IntegerField()),
                ('idNx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nxenesi')),
                ('idProfesori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profesori')),
            ],
        ),
    ]
