# Generated by Django 2.1.5 on 2019-01-14 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='IdPerioda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.perioda'),
        ),
        migrations.AddField(
            model_name='nota',
            name='idLenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.lenda'),
        ),
    ]
