# Generated by Django 2.1.5 on 2019-01-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190114_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='vlera',
            field=models.IntegerField(default=0),
        ),
    ]
