# Generated by Django 2.1.5 on 2019-01-19 10:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_notaperfundimtare'),
    ]

    operations = [
        migrations.CreateModel(
            name='mungesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataNota', models.DateTimeField(default=datetime.datetime.now)),
                ('ora', models.IntegerField(default=0)),
                ('arsyeja', models.BooleanField(default=False)),
                ('idNx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nxenesi')),
                ('idProfesori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profesori')),
            ],
        ),
    ]
