# Generated by Django 2.1.5 on 2019-01-19 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_mungesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='oraMesimore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataOres', models.DateTimeField(default=datetime.datetime.now)),
                ('titulliOres', models.CharField(max_length=50)),
                ('pershkrimiOres', models.TextField(max_length=255)),
                ('nrOra', models.IntegerField()),
                ('idLenda', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.lenda')),
                ('idProfesori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profesori')),
            ],
        ),
        migrations.AlterField(
            model_name='mungesa',
            name='arsyeja',
            field=models.BooleanField(),
        ),
    ]
