# Generated by Django 2.1.5 on 2019-01-26 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190119_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasa',
            name='idProfi',
            field=models.ForeignKey(default='Zgjedh Profesorin', on_delete=django.db.models.deletion.CASCADE, to='home.profesori'),
        ),
    ]
