# Generated by Django 2.1.5 on 2019-02-02 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('home', '0014_auto_20190126_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='userpuntori',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='b', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pozita', models.IntegerField(default=1)),
                ('idLenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lenda')),
            ],
        ),
    ]
